---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: doc-home-ops-private-git
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: doc-home-ops-private-git
    template:
      type: kubernetes.io/ssh-auth
      data:
        identity: "{{ .private_key }}"
        ssh-privatekey: "{{ .private_key }}"
        known_hosts: "{{ .known_hosts }}"
  data:
    - secretKey: private_key
      remoteRef:
        key: flux-doc-home-ops-private
        property: private_key
    - secretKey: known_hosts
      remoteRef:
        key: flux-doc-home-ops-private
        property: known_hosts
