---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: doc-home-ops-private
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/D-o-c-labs/Doc-Home-ops-private.git
  recurseSubmodules: true
  ref:
    branch: main
  secretRef:
    name: doc-home-ops-private-git
