---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wekan-mongodb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wekan-mongodb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MONGO_INITDB_ROOT_USERNAME: "{{ .wekan_mongo_root_username }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ .wekan_mongo_root_password }}"
  dataFrom:
    - extract:
        key: wekan
      rewrite:
        - regexp:
            source: "(.*)"
            target: "wekan_$1"
