---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: wekan-mongodb
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: wekan-mongodb
  ingress:
    # wekan
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: wekan
            k8s:io.kubernetes.pod.namespace: selfhosted
      toPorts:
        - ports:
            - port: "27017"
              protocol: TCP
