---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wekan
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wekan-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MONGO_URL: >-
          mongodb://{{ .wekan_mongo_root_username }}:{{ .wekan_mongo_root_password }}@wekan-mongodb.selfhosted.svc.cluster.local:27017/wekan?authSource=admin
  dataFrom:
    - extract:
        key: wekan
      rewrite:
        - regexp:
            source: "(.*)"
            target: "wekan_$1"
