---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-ingress-lan
spec:
  endpointSelector:
    matchLabels:
      ingress.home.arpa/lan: "allow"
  ingress:
    - fromCIDRSet:
        - cidr: "192.168.32.0/24"
        - cidr: "192.168.3.0/24"
        - cidr: "192.168.4.0/24"
        - cidr: "192.168.40.0/24"
