---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lobechat-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lobechat-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:

        # LLMs
        # OpenRouter Key
        OPENROUTER_API_KEY: "{{ .openrouter_api_key }}"

        # OpenAI
        OPENAI_API_KEY: "{{ .openai_api_key }}"

        # ACCESS_CODE: "{{ .lobechat_access_code }}"
        KEY_VAULTS_SECRET: "{{ .lobechat_access_code }}"

        # Authentik
        NEXT_AUTH_SECRET: "{{ .lobechat_auth_secret }}"
        NEXT_AUTH_SSO_PROVIDERS: "authentik"
        AUTHENTIK_CLIENT_ID: "{{ .authentik_lobechat_client_id }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .authentik_lobechat_client_secret }}"
        AUTHENTIK_ISSUER: "{{ .authentik_lobechat_config_issuer }}"
        NEXTAUTH_URL: "https://${HOSTNAME}/api/auth/"

        # s3
        S3_ACCESS_KEY_ID: "{{ .minio_lobechat_access_key }}"
        S3_SECRET_ACCESS_KEY: "{{ .minio_lobechat_secret }}"
        S3_ENDPOINT: "http://{{ .minio_bucket_host }}"
        S3_BUCKET: "{{ .minio_lobechat_bucket_name }}"
        S3_PUBLIC_DOMAIN: "http://{{ .minio_bucket_host }}" # Not working yet


  dataFrom:
    - extract:
        key: openrouter
      rewrite:
        - regexp:
            source: "(.*)"
            target: "openrouter_$1"
    - extract:
        key: openai
      rewrite:
        - regexp:
            source: "(.*)"
            target: "openai_$1"
    - extract:
        key: lobechat
      rewrite:
        - regexp:
            source: "(.*)"
            target: "lobechat_$1"
    - extract:
        key: authentik
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
    - extract:
        key: minio
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lobechat-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: lobechat-db-secret
    template:
      type: Opaque
      data:
        #DATABASE_URL: '{{ index . "uri" }}'
        DATABASE_URL: postgres://{{ index . "user" }}:{{ index . "password" }}@{{ index . "host" }}.cluster.local:{{ index . "port" }} # solves this commit https://github.com/lobehub/lobe-chat/commit/fdaa1909516ba3fce784a1c0c5c890a6bce2da9a
  dataFrom:
    - extract:
        key: postgres-pguser-lobechat
