---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./big-agi/ks.yaml
  - ./browserless/ks.yaml
  - ./ghostfolio/ks.yaml
  # - ./librechat/ks.yaml
  - ./lobechat/ks.yaml
  # - ./tandoor/ks.yaml
  # - ./babybuddy/ks.yaml
