---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-wasabi
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 1 * * *"
  restic:
    copyMethod: Snapshot
    repository: ${APP}-volsync-wasabi
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-synology-csi-delete}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-synology-csi-delete}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-2000}
      runAsGroup: ${APP_GID:-2000}
      fsGroup: ${APP_GID:-2000}
    pruneIntervalDays: 14
    retain:
      daily: 14