---
version: "3.4"

services:
  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:v0.26.0-ee@sha256:5ec047e4cac726f868955a34152eeff80922b958f031b10003a14cd25d6b979d
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    restart: always
    volumes:
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
      - mosquitto_data:/etc/netmaker
    environment:
      SERVER_NAME: "broker.netmaker.piscio.net"
      SERVER_HOST: "5.75.138.39"
      SERVER_API_CONN_STRING: "api.netmaker.piscio.net:443"
      COREDNS_ADDR: "5.75.138.39"
      DNS_MODE: "on"
      SERVER_HTTP_HOST: "api.netmaker.piscio.net"
      API_PORT: "8081"
      CLIENT_MODE: "on"
      MASTER_KEY: ${MASTER_KEY}
      CORS_ALLOWED_ORIGIN: "*"
      DISPLAY_KEYS: "on"
      DATABASE: "sqlite"
      NODE_ID: "netmaker-server-1"
      MQ_HOST: "mq"
      MQ_PORT: "443"
      MQ_SERVER_PORT: "1883"
      HOST_NETWORK: "off"
      VERBOSITY: "1"
      MANAGE_IPTABLES: "on"
      PORT_FORWARD_SERVICES: "dns"
      METRICS_EXPORTER: "on"
      LICENSE_KEY: ${LICENSE_KEY}
      NETMAKER_ACCOUNT_ID: ${NETMAKER_ACCOUNT_ID}
      MQ_ADMIN_PASSWORD: ${MQ_ADMIN_PASSWORD}
    ports:
      - "51821-51830:51821-51830/udp"
  netmaker-ui:
    container_name: netmaker-ui
    image: gravitl/netmaker-ui:v0.26.0@sha256:4f574a1a52bb66e786063570d8a3b45e2ad9ea9a61902a02ab021c973684fc5b
    depends_on:
      - netmaker
    links:
      - "netmaker:api"
    restart: always
    environment:
      BACKEND_URL: "https://api.netmaker.piscio.net"
  caddy:
    image: caddy:2.8.4@sha256:63d8776389cc6527e4a23bd9750489dc661923cffc3b9d7e0c20e062fa0325ec
    container_name: caddy
    restart: unless-stopped
    volumes:
      - /root/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_conf:/config
    ports:
      - "80:80"
      - "443:443"
  coredns:
    container_name: coredns
    image: coredns/coredns@sha256:9caabbf6238b189a65d0d6e6ac138de60d6a1c419e5a341fbbb7c78382559c6e
    command: -conf /root/dnsconfig/Corefile
    depends_on:
      - netmaker
    restart: always
    volumes:
      - dnsconfig:/root/dnsconfig
  mq:
    container_name: mq
    image: eclipse-mosquitto:2.0.20-openssl@sha256:090d745b6435d10a31acb82eee999ec36a2d7f416cc4f578c0a298c42af2ea14
    depends_on:
      - netmaker
    restart: unless-stopped
    command: ["/mosquitto/config/wait.sh"]
    environment:
      NETMAKER_SERVER_HOST: "https://api.netmaker.piscio.net"
    volumes:
      - /root/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /root/wait.sh:/mosquitto/config/wait.sh
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    ports:
      - "1883:1883"
      - "8883:8883"
  prometheus:
    container_name: prometheus
    image: gravitl/netmaker-prometheus:latest@sha256:e6d2ed04580b6a66fb1f1860388bf586d351b4888a465869e0bc03da3fca1cbf
    environment:
      NETMAKER_METRICS_TARGET: "netmaker-exporter.netmaker.piscio.net"
      LICENSE_KEY: ${LICENSE_KEY}
    restart: always
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - netmaker
  grafana:
    container_name: grafana
    image: gravitl/netmaker-grafana:latest@sha256:fa77971e04116ede9b1ea2547020a83a3939df39e25db5905e2047861765dce8
    environment:
      PROMETHEUS_HOST: "prometheus.netmaker.piscio.net"
      NETMAKER_METRICS_TARGET: "netmaker-exporter.netmaker.piscio.net"
      LICENSE_KEY: ${LICENSE_KEY}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    links:
      - prometheus
    depends_on:
      - prometheus
      - netmaker
  netmaker-exporter:
    container_name: netmaker-exporter
    image: gravitl/netmaker-exporter:latest@sha256:958ff96c6094d3daeb8648e6766dc64ac206ef5ddf053926e8dcebc0b29204e6
    restart: always
    depends_on:
      - netmaker
    environment:
      MQ_HOST: "mq"
      MQ_PORT: "443"
      MQ_SERVER_PORT: "1883"
      PROMETHEUS: "on"
      VERBOSITY: "1"
      API_PORT: "8085"
      LICENSE_KEY: ${LICENSE_KEY}
      PROMETHEUS_HOST: https://prometheus.netmaker.piscio.net
volumes:
  caddy_data: {}
  caddy_conf: {}
  sqldata: {}
  dnsconfig: {}
  mosquitto_data: {}
  mosquitto_logs: {}
  prometheus_data: {}
  grafana_data: {}
