---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metamcp-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: metamcp-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BETTER_AUTH_SECRET: "{{ .metamcp_better_auth_secret }}"
        # ENCRYPTION_KEY: "{{ .metamcp_encryption_key }}"
        OIDC_CLIENT_ID: "{{ .authentik_metamcp_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .authentik_metamcp_client_secret }}"
        OIDC_DISCOVERY_URL: "{{ .authentik_metamcp_discovery_url }}"
  dataFrom:
    - extract:
        key: metamcp
      rewrite:
        - regexp:
            source: "(.*)"
            target: "metamcp_$1"
    - extract:
        key: authentik
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metamcp-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: metamcp-db-secret
    template:
      type: Opaque
      data:
        # yamllint disable rule:quoted-strings
        POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        POSTGRES_DB: '{{ index . "dbname" }}'
        DATABASE_URL: 'postgresql://{{ index . "user" }}:{{ index . "password" }}@{{ index . "pgbouncer-host" }}:{{ index . "pgbouncer-port" }}/{{ index . "dbname" }}'
        # DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
        # yamllint enable rule:quoted-strings
  dataFrom:
    - extract:
        key: postgres-pguser-metamcp
