---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-external-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - port=20490
    - mountport=20490
    - proto=tcp
    - nolock
  nfs:
    server: piscionas.piscio.net
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-external-nfs
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: plex-external-nfs
