---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeassistant-secrets
  namespace: home-automation
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homeassistant-secrets
    creationPolicy: Owner
  data:
    - secretKey: LLToken
      remoteRef:
        key: home-assistant
        property: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-jupyter-secret
  namespace: home-automation
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-jupyter-secret
    creationPolicy: Owner
  data:
    - secretKey: kernel.json
      remoteRef:
        key: home-assistant
        property: kernel.json
    - secretKey: pyscript.conf
      remoteRef:
        key: home-assistant
        property: pyscript.conf


# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: home-assistant
#   namespace: home-automation
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: onepassword-connect
#   target:
#     name: home-assistant-secret
#     creationPolicy: Owner
#     template:
#       engineVersion: v2
#       data:
#         # Deploy key
#         GH_DEPLOY_KEY: "{{ .hass_github_deploy_key }}"

#         # Home-Assistant
#         SECRET_INTERNAL_URL: https://domo.bjw-s.dev
#         SECRET_INTERNAL_URL_DIRECT: http://10.1.3.151:8123
#         SECRET_EXTERNAL_URL: https://domo.bjw-s.dev
#         SECRET_TRUSTED_PROXIES_1: 10.244.0.0/16

#         # Home-Assistant Zones
#         SECRET_ZONE_HOME_HOUSE_NUMBER: "{{ .hass_zone_home_house_number }}"
#         SECRET_ZONE_HOME_POSTAL_CODE: "{{ .hass_zone_home_postal_code }}"
#         SECRET_ZONE_HOME_ELEVATION: "{{ .hass_zone_home_elevation }}"
#         SECRET_ZONE_HOME_LATITUDE: "{{ .hass_zone_home_latitude }}"
#         SECRET_ZONE_HOME_LONGITUDE: "{{ .hass_zone_home_longitude }}"
#   dataFrom:
#     - extract:
#         key: home-assistant
#       rewrite:
#         - regexp:
#             source: "(.*)"
#             target: "hass_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: home-assistant-db-secret
    template:
      type: Opaque
      data:
        SECRET_RECORDER_DB_URL: '{{ index . "uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-home-assistant
