---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcements
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  serviceSelector: {}
  loadBalancerIPs: true
