---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speech-to-phrase
  namespace: home-automation
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: speech-to-phrase-secret
    creationPolicy: Owner
  data:
    - secretKey: hass_token
      remoteRef:
        key: speech-to-phrase # update to your 1Password item
        property: hass_token # long-lived access token for Home Assistant
