---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: speech-to-phrase
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: speech-to-phrase
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: home-assistant
      toPorts:
        - ports:
            - port: "10300"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: home-assistant
            k8s:io.kubernetes.pod.namespace: home-automation
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
